root = "."
tmp_dir = "build"

[build]
cmd = "go build -o ./build/air cmd/web/main.go"
bin = "./build/air"
full_bin = "./build/air"
log = "air_errors.log"
include_ext = ["go", "tpl", "tmpl", "html", "yml", "toml", "env"]
exclude_dir = ["node_modules", "public", "resources", "Dev", "bin", "build", "dist", "docker", "storage", "tmp", "database", "docs"]
delay = 1000
