services:
  db:
    image: postgres:16.4-alpine
    hostname: gfly-db
    container_name: gfly-db
    environment:
      POSTGRES_DB: gfly
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      SERVICE_NAME: gfly-db
      SERVICE_5432_NAME: gfly-db
      SERVICE_54320_NAME: gfly-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d gfly" ]
      interval: 3s
      timeout: 3s
      retries: 10

  mail:
    image: axllent/mailpit
    hostname: gfly-mail
    container_name: gfly-mail
    labels:
      SERVICE_NAME: gfly-mail
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      # No TLS
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      # TLS
      #MP_SMTP_TLS_CERT: /data/cert.pem
      #MP_SMTP_TLS_KEY: /data/key.pem
      MP_SMTP_AUTH_FILE: /data/authfile
      TZ: Europe/London
    volumes:
      - ./mailpit:/data

  redis:
    image: redis:7.4.0-alpine
    hostname: gfly-redis
    container_name: gfly-redis
    labels:
      SERVICE_NAME: gfly-redis
    ports:
      - "6379:6379"
    env_file:
      - redis/redis.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
